environment:

  matrix:
    - PYTHON: "C:\\Python37-x64"

install:
  - "%PYTHON%\\python.exe -m pip install pyinstaller pywin32"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe setup.py install"

build: off

test_script:
  - "%PYTHON%\\python.exe -m PyInstaller.__main__ --onefile bin\\interactive_ocr.py"
  - "%PYTHON%\\python.exe -m PyInstaller.__main__ --onefile bin\\convert_ocr.py"

artifacts:
  - path: dist
